name: housing-price-regression
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-tools@v1
      - name: Run training and metrics
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py
          
          echo "## Model metrics" > report.md 
          cat metrics.txt >> report.md

          echo "## Data Viz" >> report.md
          cml comment create "![Feature Importance](./feature_importance.png)" >> report.md
          cml comment create "![Residuals](./residuals.png)" >> report.md

          # Publish the report
          cml comment create < report.md
          
